-- 整数主键重建 + entry_price + 盘中概率列
-- 注意：会清空四张业务表

drop table if exists judgments cascade;
drop table if exists runs cascade;
drop table if exists holdings cascade;
drop table if exists watchlist cascade;

create table watchlist (
  id integer generated by default as identity primary key,
  market text not null check (market in ('sh', 'sz', 'bj')),
  code text not null,
  name text not null,
  source text not null check (source in ('ai', 'manual')),
  score numeric null,
  entry_price numeric null,
  latest_buy_probability numeric null,
  latest_buy_at timestamptz null,
  added_at timestamptz not null default now(),
  unique (market, code)
);

create table holdings (
  id integer generated by default as identity primary key,
  market text not null check (market in ('sh', 'sz', 'bj')),
  code text not null,
  name text not null,
  quantity int not null check (quantity > 0),
  entry_price numeric null,
  latest_sell_probability numeric null,
  latest_sell_at timestamptz null,
  added_at timestamptz not null default now(),
  unique (market, code)
);

create table runs (
  id integer generated by default as identity primary key,
  type text not null check (type in ('discover', 'poll')),
  status text not null check (status in ('running', 'completed')),
  progress jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  finished_at timestamptz null
);

create table judgments (
  id integer generated by default as identity primary key,
  run_id integer not null references runs(id) on delete cascade,
  market text not null,
  code text not null,
  kind text not null check (kind in ('score', 'buy', 'sell')),
  probability numeric not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index judgments_market_code_created_idx
  on judgments (market, code, created_at desc);

create index runs_status_type_idx
  on runs (status, type, created_at desc);

alter table watchlist enable row level security;
alter table holdings enable row level security;
alter table runs enable row level security;
alter table judgments enable row level security;
